package com.example.service

import android.app.Notification
import android.content.pm.PackageManager
import android.service.notification.NotificationListenerService
import android.service.notification.StatusBarNotification
import android.util.Log
import androidx.core.app.NotificationCompat
import com.example.data.AppDatabase
import com.example.data.NotificationEntity
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch

class NotificationCaptureService : NotificationListenerService() {

    private val serviceScope = CoroutineScope(Dispatchers.IO + SupervisorJob())
    private val recentPayloads = LinkedHashMap<String, Long>()

    override fun onDestroy() {
        super.onDestroy()
        serviceScope.cancel()
    }

    override fun onNotificationPosted(sbn: StatusBarNotification?) {
        super.onNotificationPosted(sbn)
        if (sbn == null) return

        val packageName = sbn.packageName ?: return
        // Self-Notification Filter: Never record notifications generated by NotiBox itself
        if (packageName == applicationContext.packageName) return

        val notification = sbn.notification ?: return
        val extras = notification.extras ?: return

        // Resolve App Name
        val appName = try {
            val appInfo = packageManager.getApplicationInfo(packageName, 0)
            packageManager.getApplicationLabel(appInfo).toString()
        } catch (e: PackageManager.NameNotFoundException) {
            packageName.substringAfterLast('.')
        } catch (e: Exception) {
            packageName
        }

        // Title Extraction Fallback Chain
        val titleBig = extras.getCharSequence(Notification.EXTRA_TITLE_BIG)?.toString()
        val titleStandard = extras.getCharSequence(Notification.EXTRA_TITLE)?.toString()
        val titleCompat = extras.getCharSequence(NotificationCompat.EXTRA_TITLE)?.toString()
        val title = when {
            !titleBig.isNullOrBlank() -> titleBig
            !titleStandard.isNullOrBlank() -> titleStandard
            !titleCompat.isNullOrBlank() -> titleCompat
            appName.isNotBlank() -> appName
            else -> "Unknown Alert"
        }.trim()

        // Body / Text Extraction
        val bigText = extras.getCharSequence(Notification.EXTRA_BIG_TEXT)?.toString()?.trim()
        val contentText = extras.getCharSequence(Notification.EXTRA_TEXT)?.toString()?.trim().orEmpty()
        val summaryText = extras.getCharSequence(Notification.EXTRA_SUMMARY_TEXT)?.toString()?.trim()
        val infoText = extras.getCharSequence(Notification.EXTRA_INFO_TEXT)?.toString()?.trim()
        val subText = extras.getCharSequence(Notification.EXTRA_SUB_TEXT)?.toString()?.trim()

        // Multi-line & Stacked Messages Extraction (EXTRA_TEXT_LINES)
        val textLines = extras.getCharSequenceArray(Notification.EXTRA_TEXT_LINES)
        val stackedFromLines = textLines?.mapNotNull { it?.toString()?.trim() }
            ?.filter { it.isNotEmpty() }
            ?.joinToString("\n")

        // MessagingStyle Extraction
        val messagingStyleLines = try {
            val messagingStyle = NotificationCompat.MessagingStyle.extractMessagingStyleFromNotification(notification)
            messagingStyle?.messages?.mapNotNull { msg ->
                val sender = msg.person?.name ?: msg.person?.key ?: ""
                val text = msg.text?.toString()?.trim()
                if (text.isNullOrBlank()) null
                else if (sender.isNotBlank()) "$sender: $text"
                else text
            }?.joinToString("\n")
        } catch (e: Exception) {
            null
        }

        val resolvedStackedLines = when {
            !messagingStyleLines.isNullOrBlank() -> messagingStyleLines
            !stackedFromLines.isNullOrBlank() -> stackedFromLines
            else -> null
        }

        val primaryContent = when {
            contentText.isNotBlank() -> contentText
            !bigText.isNullOrBlank() -> bigText
            !resolvedStackedLines.isNullOrBlank() -> resolvedStackedLines
            !summaryText.isNullOrBlank() -> summaryText
            else -> ""
        }

        // If completely empty payload without useful metadata, skip
        if (title.isBlank() && primaryContent.isBlank() && resolvedStackedLines.isNullOrBlank()) {
            return
        }

        val postTime = sbn.postTime.takeIf { it > 0 } ?: System.currentTimeMillis()

        // Deduplication: Skip consecutive identical payloads from same package within 2 seconds
        val dedupeKey = "$packageName|$title|$primaryContent|$resolvedStackedLines"
        synchronized(recentPayloads) {
            val lastSeen = recentPayloads[dedupeKey]
            if (lastSeen != null && (postTime - lastSeen) < 2000L) {
                return
            }
            recentPayloads[dedupeKey] = postTime
            // Clean older entries
            if (recentPayloads.size > 200) {
                val oldestKeys = recentPayloads.keys.take(50).toList()
                oldestKeys.forEach { recentPayloads.remove(it) }
            }
        }

        val primaryContentLower = primaryContent.lowercase()
        val isRevokedMarker = primaryContentLower.contains("this message was deleted") ||
                primaryContentLower.contains("this message was unsent") ||
                primaryContentLower.contains("message was deleted") ||
                primaryContentLower.contains("unsent a message")

        val isPromo = notification.category == Notification.CATEGORY_PROMO ||
                primaryContentLower.contains("sale") ||
                primaryContentLower.contains("discount") ||
                primaryContentLower.contains("limited time")

        val entity = NotificationEntity(
            packageName = packageName,
            appName = appName,
            title = title,
            content = primaryContent,
            bigText = bigText,
            summaryText = summaryText,
            infoText = infoText,
            subText = subText,
            stackedLines = resolvedStackedLines,
            category = notification.category,
            postTime = postTime,
            notificationId = sbn.id,
            tag = sbn.tag,
            key = sbn.key,
            isOngoing = sbn.isOngoing,
            isCategoryPromo = isPromo
        )

        serviceScope.launch {
            try {
                val db = AppDatabase.getDatabase(applicationContext)
                val dao = db.notificationDao()
                
                if (isRevokedMarker) {
                    val latestMsg = dao.getLatestMessageForRevocation(packageName, title)
                    if (latestMsg != null && (postTime - latestMsg.postTime) < 15 * 60 * 1000L) { // Within last 15 mins
                        dao.markAsRevoked(latestMsg.id, postTime)
                        return@launch // Skip inserting the "deleted" stub message
                    }
                }

                // Double check recent in DB within 2s to be 100% deduplicated
                val latestTime = dao.getLatestDuplicateTime(packageName, title, primaryContent)
                if (latestTime != null && (postTime - latestTime) < 2000L) {
                    return@launch
                }
                dao.insertNotification(entity)
            } catch (e: Exception) {
                Log.e("NotiBoxService", "Error saving notification", e)
            }
        }
    }
}
